default:
  image: node:18-alpine
  before_script:
    # install pnpm
    - wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

stages:
  - lint
  - test
  - e2e
  - build

lint:
  stage: lint
  script:
    - pnpm install
    - pnpm lint

test:
  stage: test
  script:
    - pnpm install
    - pnpm test

e2e:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.29.0-focal
  # to boost execution speed if needed - apply sharding https://playwright.dev/docs/ci#sharding-1
  script:
    - pnpm install
    - pnpm e2e
  artifacts:
    paths:
      - '**/playwright-report'
      - '**/test-results'

build:
  stage: build
  script:
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - '**/dist'
      - '**/build'
